# Generated by Django 5.2 on 2026-03-18 11:21

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityMembership',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner (Full Control)'), ('MANAGER', 'Site Manager (Can Edit)'), ('VIEWER', 'Viewer (Read Only)')], default='VIEWER', max_length=10)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'entity')},
            },
        ),
        migrations.AddField(
            model_name='entity',
            name='users',
            field=models.ManyToManyField(related_name='accessible_entities', through='entity.EntityMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
