# Generated by Django 6.0.1 on 2026-03-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_entitymembership_entity_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entity',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'guest'), ('REGISTERED', 'public'), ('RESTRICTED', 'Restricted'), ('HIDDEN', 'Hidden')], default='PUBLIC', max_length=20),
        ),
    ]
