# Generated by Django 6.0.1 on 2026-03-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_entity_is_hidden_entity_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='external_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='external_file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='storage_backend',
            field=models.CharField(choices=[('LOCAL', 'Local'), ('GDRIVE', 'Google Drive'), ('S3', 'Amazon S3')], default='LOCAL', max_length=20),
        ),
    ]
